name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build DEB
      run: |
        dpkg --add-architecture arm
        apt-get update
        apt-get install pkg-config build-essential crossbuild-essential-arm64
        rustup target add aarch64-unknown-linux-gnu
        cargo install cargo-deb
        cargo deb --target=aarch64-unknown-linux-gnu
        cargo deb
        
        
